### PR TITLE
Issue 400- Readme for NASNet

### PR DESCRIPTION
**Pull request by srimontidutta**
Added the readme file "FR_README.md" - Improved readme file for face recognition with NASNet.
 #400

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
why you have named it files-to-merge

**Comment by srimontidutta** [comment]
> why you have named it files-to-merge

@akshitagupta15june I named it "FR_README.md".

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
why you have added a pencil sketch it is already implemented.

**Comment by akshitagupta15june** [comment]
please add only nasnet readme

**Comment by srimontidutta** [comment]
> please add only nasnet readme

Oh! I must have made a mistake then, because I was assigned to the pencil sketch readme as well and my PR for that was already merged a few days ago. Would you merge my nasnet readme from the existing PR or should I create a separate branch and make another PR?

**Review by akshitagupta15june — APPROVED** [review]
approving

**Comment by srimontidutta** [comment]
Thanks! @akshitagupta15june

**Pull request merged**
