### PR TITLE
Added Face Alignment in Full Pose Range

### PR DESCRIPTION
**Pull request by infiniteoverflow**
Fixes: #169 
# Proposed Changes
 This model holds the pytorch improved version of the paper: [Face Alignment in Full Pose Range: A 3D Total Solution.](https://arxiv.org/abs/1804.01005)
 
# Applications
- Face Reconstruction
- Face Alignment
- 3D Pose Estimation
- Depth Image Estimation

@akshitagupta15june The applications are diverse but currently i have added this model in the `Face Reconstruction` folder. I can later change it if required.

### CODE REVIEW

**Review by akshitagupta15june — COMMENTED** [review]
Great @infiniteoverflow I am impressed by your level of contribution and research!
Now It's a request from my side as this project is under various open source program and your most contributions are in FACE RECONSTRUCTION  so you have to share your research and contribution with the mentees and me.

**Review by akshitagupta15june — APPROVED** [review]

**Comment by infiniteoverflow** [comment]
Thanks a lot @akshitagupta15june , can i know what i should do , will be glad to share my work.

**Comment by akshitagupta15june** [comment]
@infiniteoverflow would you like to be the mentor for face reconstruction in this repo?
The mentees in open source programs will be happy to learn from you.
like i will inform you and invite you for a session with them.
can you share your mailid here.

**Comment by infiniteoverflow** [comment]
Sure, i will be glad to. I will message you the details in DM. Thank you.

**Comment by akshitagupta15june** [comment]
thankyou so much!

**Pull request merged**
