### PR TITLE
Added flower crown and witch hat filter

### PR DESCRIPTION
**Pull request by sherin527**
@akshitagupta15june ma'am, I've added flower crown and witch hat filter. I'm GSSOC'21 participant, do check it and review it.

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
can you add a proper readme showing your implementation with an output screenshot?
A screenshot of yours is not necessary you can test in any celebrity image

**Comment by sherin527** [comment]
@akshitagupta15june, yes ma'am, I'll do it.

**Comment by sherin527** [comment]
@akshitagupta15june ma'am, I've updated readme file, please check it .

**Review by akshitagupta15june — APPROVED** [review]
Great @sherin527

**Comment by sherin527** [comment]
Thank you, @akshitagupta15june ma'am

**Pull request merged**
