### PR TITLE
Added Play Pause of Video with Eye Wink Face Detection

### PR DESCRIPTION
**Pull request by MihirRajeshPanchal**
# Related Issues or bug
  #1309 Issue Solved

Fixes: #[issue number that will be closed through this PR]

# Proposed Changes
 -hey @MihirRajeshPanchal try to implement it using facial blink or mouth expression but not hand because as it a repo for face related operations
The above comment was looked into and made the necessary changes

### CODE REVIEW

**Comment by MihirRajeshPanchal** [comment]
@akshitagupta15june Please look into it

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Please add screen shot or video link

**Review by 072arushi — APPROVED** [review]

**Review by harsh5902 — CHANGES_REQUESTED** [review]
good !
also add your game name and description in Face-X-Gaming/readme.md table.
and add a screenshot or any video which could show your project.

**Comment by MihirRajeshPanchal** [comment]
@harsh5902 @072arushi I have added the output image too

**Review by harsh5902 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Comment by MihirRajeshPanchal** [comment]
@akshitagupta15june reviewers have reviewed the pr

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hey Mihir wonderful implementation I suggest you to add some more details in readme like how you implemented and also instead of adding a downloaded video try to add a youtube video link in output.

**Review by harshit-paneri — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
@MihirRajeshPanchal please work on according to above comments

**Comment by akshitagupta15june** [comment]
@MihirRajeshPanchal are u working on this?

**Comment by MihirRajeshPanchal** [comment]
Yes I am working

**Comment by MihirRajeshPanchal** [comment]
https://github.com/MihirRajeshPanchal/Face-X/commit/7507137a86d5e9b5b38636e63dc16fd0297ab3ba

**Review by akshitagupta15june — APPROVED** [review]
wonderful! thanks for contributing

**Pull request merged**
