### PR TITLE
Face Recognition using Resnet50

### LINKED ISSUE #20: Recognition using Resnet50
@akshitagupta15june  Can  work on this?

### PR DESCRIPTION
**Pull request by Halix267**
closes #20

### CODE REVIEW

**Comment by Halix267** [comment]
@akshitagupta15june Plzz review it.

**Comment by Halix267** [comment]
Screenshot from 2020-12-11 21-34-18

Screenshot from 2020-12-11 21-37-19

**Comment by Halix267** [comment]
Screenshot from 2020-12-11 21-40-08

See I think Resnet50 is better than using cnn bcz it can recognise image at this much distance also

**Comment by akshitagupta15june** [comment]
Can you please add a readme file showing procedure as well as outputs
It will be great

**Comment by akshitagupta15june** [comment]
I have seen the output it's good but it will be better if you also add a readme with every pr

**Comment by Halix267** [comment]
ok i will add it asap

**Pull request closed without merging**
