### PR TITLE
Added virtual makeover

### PR DESCRIPTION
**Pull request by mehabhalodiya**
# Related Issue or bug
  - Creates virtual makeover

Fixes: #68 Virtual makeover of a face by facial landmark detection

# Proposed Changes
 - Added Virtual makeover using PIL library. You can easily run digital_makeup.py file

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
I am JWOC mentee. Kindly check this @akshitagupta15june .

**Review by akshitagupta15june — APPROVED** [review]
Can you add a proper readme file expalining your implementation.
Also if it is possible include a celebrity or character static image showing the output.

**Comment by akshitagupta15june** [comment]
@mehabhalodiya you can check other readme how they are made.

**Comment by mehabhalodiya** [comment]
@akshitagupta15june ma'am, done as per your instructions!

**Review by akshitagupta15june — APPROVED** [review]
Great work!

**Pull request merged**
