### PR TITLE
Added Cartoonify face image script.

### PR DESCRIPTION
**Pull request by amandp13**
# Cartoonifying a face image.
- Converting a facial Image to Cartoon Using OpenCV.

Fixes: #53 
 
# Screenshots
    
|  Before
face

|  Output

after_face
|

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Are you a nwoc swoc or dwoc participant?

**Comment by amandp13** [comment]
@akshitagupta15june SWOC 2021 Participant

**Review by saurabhshahane4 — APPROVED** [review]
Changes approved!

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
@amandp13 great work!

**Pull request merged**
