### PR TITLE
Makeup Detection 

### PR DESCRIPTION
**Pull request by Shreyg-27**
# Related Issues or bug
  - This makeup detection model takes input as an image and detects whether a person has applied makeup or not. 

Fixes: #1542 
# Proposed Changes
 - I have created a folder of Makeup Recognition, and in that, I have a directory of the dataset (subdirectories-Makeup and No Makeup), along with the model, and the README file.

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Please add a proper readme with screenshot of output, accuracy also how to run it

**Comment by Shreyg-27** [comment]
> Please add a proper readme with screenshot of output, accuracy also how to run it

Hi @akshitagupta15june!
I have added the content in the README.md file, along with the output screenshots. Hope it is fine now. 
Thank you!

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
please add all ur implementation inside the virtual makeover folder

**Comment by Shreyg-27** [comment]
> please add all ur implementation inside the virtual makeover folder

Hi @akshitagupta15june! I have added the implementation in the Virtual Makeover Folder.

**Review by akshitagupta15june — APPROVED** [review]
Good work!!

**Pull request merged**
