### PR TITLE
#286 

### PR DESCRIPTION
**Pull request by anubhav201241**
# Related Issue or bug
  - The code is not fully optimized and completed 

Fixes: #286

# Proposed Changes
 - Add some features on it and try to make it easier and optimized 
 
# Additional Info
  - Thank you for assigning me for my first contribution I' tried my best to make the code look easy to read  :)

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hi you have ceated two new codes which is not allowed and also you have put them inside different folders

**Comment by anubhav201241** [comment]
Thank you for telling my mistake I surely try to work upon it, Thank you

**Comment by anubhav201241** [comment]
Can you assigned this task me again I will try to improve it

**Review by akshitagupta15june — APPROVED** [review]
merged

**Pull request merged**
