### PR TITLE
Readme added for face detection folder

### PR DESCRIPTION
**Pull request by prajaktanandawade**
Readme added for face detection folder.
I am looking to contribute to this project and will improve the read me.

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hi, @prajaktanandawade images are not visible and I can only see the code link.
Can you add some content too like the installation process and all?
you can look at another readme in this repo for help.

**Comment by prajaktanandawade** [comment]
Changes updated successfully.

**Comment by akshitagupta15june** [comment]
hi @prajaktanandawade https://github.com/akshitagupta15june/Face-X/tree/master/Cartoonify%20Image have a look at this readme like if user want to execute any code from this repo so will they start executing.

**Comment by akshitagupta15june** [comment]
are u making changes @prajaktanandawade ?

**Pull request closed without merging**
