### PR TITLE
Cartoonifying

### PR DESCRIPTION
**Pull request by akshitagupta15june**
# Related Issuse or bug
  - Info about Issue or bug

Fixes: #[issue number that will be closed through this PR]

# Proposed Changes
 - Info about changes Goes here
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot **|

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
@SoyabulIslamLincoln like i have done this from my side

**Comment by akshitagupta15june** [comment]
You did a small mistake like you tried to merge it in your master branch

**Comment by akshitagupta15june** [comment]
Hii in readme file i can see no such difference in two images
Can you please look at that issue and update it

**Comment by SoyabulIslamLincoln** [comment]
Okay. I am getting onto it right away.

**Pull request merged**
