### PR TITLE
snapchat_mask

### PR DESCRIPTION
**Pull request by Teju-g49**
_#_ Related Issues or bug
  - Info about Issue or bug

Fixes: #66     

# Proposed Changes
 - Info about changes Goes here
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot **|

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Please create a readme expalining your implementation with screenshots of output

**Comment by akshitagupta15june** [comment]
i am closing this pr as changes not made by @Teju-g49

**Comment by Teju-g49** [comment]
Will you please allow me some time ?

**Comment by akshitagupta15june** [comment]
Yeah!
Reopening the issue

**Comment by akshitagupta15june** [comment]
@Teju-g49 are you still working in this?

**Comment by Teju-g49** [comment]
Yes

**Pull request closed without merging**
