### PR TITLE
Adding the Negative/Invert Filter

### PR DESCRIPTION
**Pull request by Aarthy153**
# Related Issues or bug
  - Info about Issue or bug

Fixes: #1244 

# Proposed Changes
 - Info about changes Goes here
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot **|

### CODE REVIEW

**Comment by Aarthy153** [comment]
Please add the hacktoberfest-accepted and SLoP 25 labels.

**Review by akshitagupta15june — APPROVED** [review]
add a output image in readme please

**Comment by Aarthy153** [comment]
Yes I will do it. Please add the hacktoberfest-accepted label to this PR. Thank you.

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
give @Aarthy153 25 points

**Pull request merged**
