### PR TITLE
Added percentage detection

### PR DESCRIPTION
**Pull request by mehabhalodiya**
# Related Issue
  Added in Face Emotions Recognition

Fixes: #178

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
@akshitagupta15june kindly check it.

**Comment by akshitagupta15june** [comment]
Good work
Can you add a proper readme!

**Comment by mehabhalodiya** [comment]
Yes, sure!
I will open a issue regarding addition of proper readme file and create a PR for this, if you allow me to do so!

**Comment by akshitagupta15june** [comment]
hi, can you create a readme without opening the issue because you have created the pr and it needs improvement.

**Comment by mehabhalodiya** [comment]
Okay, got it!
Thank you!

**Comment by mehabhalodiya** [comment]
@akshitagupta15june I have added proper README file.

**Review by akshitagupta15june — APPROVED** [review]
great

**Pull request merged**
