### PR TITLE
Adding new filter

### PR DESCRIPTION
**Pull request by BlueBlaze6335**
Hello ,
I have created a filter - Thug Life Filter , added with a music playing in the background , similar to snapchat filters with music. This is a funny filter. It would be kind of you to merge my request !! Thank you.

Regards ,
Padmanabha Banerjee
(BlueBlaze6335)

### CODE REVIEW

**Comment by BlueBlaze6335** [comment]
I have also added a new face recognizing solution  , added to the master directory. Please check !!!

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hi @BlueBlaze6335 can you please create a single pr showing your snap chat filter.
For the new recognition ytechnique you can create a different pr and along with issue first

**Comment by akshitagupta15june** [comment]
@BlueBlaze6335 please create a single pr showing your implementation of snapchat filter only.

**Comment by BlueBlaze6335** [comment]
@akshitagupta15june  Okay.

**Pull request closed without merging**
