### PR TITLE
Uploaded Snapchat Clown Nose Filter/issue1229

### PR DESCRIPTION
**Pull request by nerdlab53**
# Related Issues or bug
- Added a clown nose filter 

Fixes: #1229

# Proposed Changes
 - Info about changes Goes here
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Screenshot of the filter
clowmn_nomse
Screenshot of using the filter
Clown_Nose_Filter

### CODE REVIEW

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Please create README.md file and put screenshot in conversation.

**Review by harshit-paneri — APPROVED** [review]

**Comment by nerdlab53** [comment]
> Please create README.md file and put screenshot in conversation.

I have created the README.md and put the screenshots in the comments as well as attached them here.
Really sorry for the inconvenience caused.

Screenshot Of Filter:
clowmn_nomse

Screenshot Of Using The Filter:
Clown_Nose_Filter

**Comment by harshit-paneri** [comment]
> > Please create README.md file and put screenshot in conversation.
> 
> I have created the README.md and put the screenshots in the comments as well as attached them here. Really sorry for the inconvenience caused.
> 
> Screenshot Of Filter: clowmn_nomse
> 
> Screenshot Of Using The Filter: Clown_Nose_Filter

Approved ✨

**Review by 072arushi — APPROVED** [review]

**Review by harsh5902 — APPROVED** [review]

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Thanks for contributing

**Pull request merged**
