### PR TITLE
Cartoon

### PR DESCRIPTION
**Pull request by shireenchand**
# Related Issues or bug
  - Differentiate cartoon images from real human faces. #929

Fixes: #929

# Proposed Changes
 - I have added a python script that differentiates Human and Cartoon Faces based on an index.
 - The methodology includes smoothing/cartoonifying the given image, taking hsv of the original and the smoothed images and then subtracting the smoothed image from the original image. Taking the mean of this subtraction gives us the index based on which it is decided whether it's a cartoon face or a human face.The index should be high for non-smooth original (natural scene) images and low for smooth original (cartoony) images.
 
# Additional Info
  - I have added test images in the Assets folder to try the script.

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hey @shireenchand good work! I saw the readme.md , I think you can add some more information like
Installation, Steps, What feature or module you have used, What are the requirements( a requirements.txt file)

**Comment by shireenchand** [comment]
Thanks! I'll make those changes

**Comment by shireenchand** [comment]
@akshitagupta15june I have made the changes. I have made a proper readme and added proper information. I have also added the requirements.txt file

**Review by akshitagupta15june — APPROVED** [review]
Awesome!

**Pull request merged**
