### PR TITLE
Updated   Cartoonification  Readme File  

### PR DESCRIPTION
**Pull request by Vi1234sh12**
# Related Issuse or bug
  [Readme Improvement for Cartoonification Readme File #437](https://github.com/akshitagupta15june/Face-X/issues/437)

# Proposed Changes
 - Info about changes Goes here
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:

### Original Readme File :  
Before_update1
 | 
### Updated Readme File : 
After_update1
|

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
can you add all your images by creating a separate folder named "images" in cartoonifiaction folder

**Comment by Vi1234sh12** [comment]
> can you add all your images by creating a separate folder named "images" in cartoonifiaction folder

Sure , no problem

**Comment by Vi1234sh12** [comment]
hey,@akshitagupta15june I'm Adding All Image Assets Folder

**Review by akshitagupta15june — APPROVED** [review]
@Vi1234sh12 awesome work!

**Pull request merged**
