### PR TITLE
Recognition using resnet50

### LINKED ISSUE #20: Recognition using Resnet50
@akshitagupta15june  Can  work on this?

### PR DESCRIPTION
**Pull request by Halix267**
closes #20

### CODE REVIEW

**Comment by Halix267** [comment]
@akshitagupta15june Plzz review it

**Comment by Halix267** [comment]
@akshitagupta15june  Also how much points do I get for this pr ?? Do I get extra 2 points each  for opening the issues in VGG19 and Resnet50 respectively????

**Comment by akshitagupta15june** [comment]
Awesome

**Comment by akshitagupta15june** [comment]
+20 points updated

**Pull request merged**
