### PR TITLE
Contributing.md

### PR DESCRIPTION
**Pull request by smriti1313**
# Related Issuse or bug
  - contributing.md was not present

Fixes: #232 

# Proposed Changes
 - contributors assests folder contains contributing.md which has details about how to make open source contributions

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Hey i think this a copied one from another project.
Please change it 
The contributing guidelines should be according to our project.

**Comment by smriti1313** [comment]
I might have copied the main headings but i followed the original github and git articles to write them and even added clear intructions in screenshots.

Is there anything thats not according to our project?

**Comment by akshitagupta15june** [comment]
start with the compilation of dlib in your system, clone the repository in some directory in your system:

```
# Clone the dlib library in some directory of the system
git clone https://github.com/davisking/dlib.git
```

Then, proceed to build dlib with the following commands:



See these commands for installation are for other project

**Comment by akshitagupta15june** [comment]
The commands for installation and setup should be related to facex right!

**Comment by smriti1313** [comment]
> start with the compilation of dlib in your system, clone the repository in some directory in your system:
> 
> ```
> # Clone the dlib library in some directory of the system
> git clone https://github.com/davisking/dlib.git
> ```
> 
> Then, proceed to build dlib with the following commands:
> 
> See these commands for installation are for other project

oh okay now i see it. i thought you asked for completely basic beginner guide as you mentioned in issue. I will add dlib now.

**Comment by smriti1313** [comment]
> The commands for installation and setup should be related to facex right!

yes yes. I will add all other details regarding complete setup of face x .

**Comment by akshitagupta15june** [comment]
Hey there are many commands that are not related to our project i am sending you a reference contributing.md

**Comment by akshitagupta15june** [comment]
@smriti1313 a reference https://github.com/HarshCasper/Rotten-Scripts/blob/master/CONTRIBUTING.md

**Comment by smriti1313** [comment]
Even though i didn't know about such a repo, i actually referred some other online contributing.md. I ll.make the necessary changes

**Comment by akshitagupta15june** [comment]
No problem @smriti1313 you can refer to this repo i mentioned

**Pull request closed without merging**
