### PR TITLE
Added emotion detection and music recommendation

### LINKED ISSUE #516: Music recommendation from emotions
I would like to add a project.
Here, I would detect emotions of a human from facial expressions and then recommend musics accordingly

### PR DESCRIPTION
**Pull request by sudipg4112001**
fixes #516

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Can you please add a proper readme

**Comment by akshitagupta15june** [comment]
are u adding it @sudipg4112001

**Comment by sudipg4112001** [comment]
> are u adding it @sudipg4112001

Yes.. give me some time

**Comment by sudipg4112001** [comment]
readme file updated. Please review

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
can you add a proper output image like what songs are being detected on running this code and how to run the code what dataset is used?

**Comment by sudipg4112001** [comment]
> can you add a proper output image like what songs are being detected on running this code and how to run the code what dataset is used?

OK..

**Comment by sudipg4112001** [comment]
@akshitagupta15june changes are made. Please review.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Can you add output in readme , I am still not able to see like what it is predicting can you try with some celebrity images and add the same

**Comment by sudipg4112001** [comment]
It's actually predicting the emotions and playing a suitable music. For, this what kind of output image can I give, nothing such is available. 
If you want me to change the output image, I can do so.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Yes thats what i am asking like somewhere you are getting a output of song recommended just take a screenshot of that , try to give random pic and whatever it suggest just add a screenshot.

**Comment by sudipg4112001** [comment]
Okay I will do. Please give me some time.. I am facing some issues.

**Comment by sudipg4112001** [comment]
@akshitagupta15june can you please confirm if the images in the readme file is visible or not.. actually I am facing some issues.

**Review by akshitagupta15june — APPROVED** [review]
Great

**Pull request merged**
