### PR TITLE
Face_Orientation_Predictor

### PR DESCRIPTION
**Pull request by UppuluriKalyani**
New Feature: Face Orientation Prediction
We are excited to announce the addition of a new feature to our project: Face Orientation Prediction using a neural network. This enhancement allows users to predict the orientation of grayscale face images, categorizing them into one of four possible orientations: straight, up, left, and right.

Feature Highlights
Data Collection: Automatically download face images from a specified URL and save them locally.
Preprocessing: Resize images to 32x30 pixels and normalize pixel values for improved model performance.
Neural Network Training: Train a neural network to classify face orientations with high accuracy.
Model Persistence: Save the trained model to a file for easy reuse and deployment.
Prediction and Visualization: Load the saved model and predict orientations for new images, with an option to visualize predictions.
How to Use
Download the Dataset:

Update the script with the URL containing face images.
Run the script to download and save the images.
Preprocess the Images:

Utilize the provided functions to resize and normalize the images.
Train the Model:

Train the neural network using the preprocessed dataset.
Save and Load the Model:

Save the trained model for future predictions.
Load the saved model to predict orientations for new images.
Visualize Predictions:

Display images with their predicted labels using the visualization functions.
We believe this feature will be incredibly useful for projects involving facial recognition, image processing, and machine learning.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Please mention issue number u have solved

**Comment by UppuluriKalyani** [comment]
#1761

**Comment by UppuluriKalyani** [comment]
Hi @akshitagupta15june mam  I noticed my pull request #1789  hasn't been assigned any labels yet. Could you please review and label it? I believe this might help me appear on the Girlscript Summer of Code leaderboard. Thanks!

**Review by akshitagupta15june — COMMENTED** [review]
Please add your implementation inside awesome face operation folder

**Comment by UppuluriKalyani** [comment]
@akshitagupta15june yes mam I have added the implementation inside the awesome face operation folder. Please review and merge this pull request at your earliest convenience mam as the GSSOC'24 leaderboard requires merged pull requests for participants to appear on the leaderboard. Thank you!

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
