### PR TITLE
issue#1115 virtual facial jewellery

### PR DESCRIPTION
**Pull request by RusJaI**
Includes the notebooks for nose stud jewellery and forehead dot jewel
(for GSSOC22 )

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Add output screenshots in readme and write some more info about how you implemented

**Comment by RusJaI** [comment]
@akshitagupta15june since  you have approved #1115 shall I remove this PR and create a new branch under that issue ID ?
And also shall I keep it under virtual makeover or place in a new directory under root?

**Comment by akshitagupta15june** [comment]
You just have to update the readme

**Comment by akshitagupta15june** [comment]
have u updated it?

**Comment by RusJaI** [comment]
> have u updated it?

yes, its' done

**Review by akshitagupta15june — APPROVED** [review]
Great work

**Pull request merged**
