### PR TITLE
Added Happy Diwali Filter #1228

### PR DESCRIPTION
**Pull request by nerdy-nakul**
# Related Issues or bug
  - Added Happy Diwali Filter

Fixes: #1228 

# Proposed Changes
 - Added a Filter
 
# Additional Info
  - Anything related Issues 
  
# Screenshots of using filter
 
Snapchat_Filters/Happy_Diwali_Filter/hampy_diwali.jpg
Snapchat_Filters/Happy_Diwali_Filter/Happy_Diwali_Filter.png

### CODE REVIEW

**Review by harshit-paneri — COMMENTED** [review]
Put screenshot in conversation

**Review by harshit-paneri — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]
Approved

**Review by harsh5902 — APPROVED** [review]

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
add a screenshots in the readme file and also steps for implementation

**Comment by nerdy-nakul** [comment]
> add a screenshots in the readme file and also steps for implementation

added screenshots & steps of implementation in README.md

**Comment by nerdy-nakul** [comment]
> Put screenshot in conversation

SCREENSHOT OF FILTER :

hampy_diwali

SCREENSHOT OF USING THE FILTER :

Happy_Diwali_Filter

**Review by akshitagupta15june — APPROVED** [review]
Wonderful implementation

**Comment by nerdy-nakul** [comment]
> Wonderful implementation

Thank you so much.

**Pull request merged**
