### PR TITLE
Added Image segmenattion using Color spaces and opencv

### PR DESCRIPTION
**Pull request by sherin527**
@akshitagupta15june ma'am, I have added the implementation of Image segmentation using color spaces and OpenCV. I will update the readme shortly.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
please mention the issue too.

**Comment by sherin527** [comment]
@akshitagupta15june ma'am, issue #366 for  Image segmentation using color spaces. I have added readme also.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
try to add all your images inside an images folder in image_segmentation and use this naming convention "image-segmentation"

**Comment by sherin527** [comment]
ok @akshitagupta15june ma'am, I'll change it.

**Comment by akshitagupta15june** [comment]
already merged

**Pull request closed without merging**
