### PR TITLE
Recognition using FIsherFaceRecogniser

### PR DESCRIPTION
**Pull request by ashwani-rathee**
This should be it but there can be need for more proper documentation.I wish to work on MTCNN and FaceNet.
It addresses #26

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Will be updating your points.
Good work.

**Comment by ashwani-rathee** [comment]
Thank you!!:)

**Comment by akshitagupta15june** [comment]
Please add a readme file too in this
Explaining the process and output

**Comment by akshitagupta15june** [comment]
Hiii i have added your points

**Comment by ashwani-rathee** [comment]
They have been updated,thanks

**Pull request merged**
