### PR TITLE
Implement Face Swapping #1132

### PR DESCRIPTION
**Pull request by ADITYADAS1999**
# Related Issues or bug
  - Implement Face Swapping #1132
    In awesome face operation folder

Fixes: #1132 

# Proposed Changes
 - To Implement Face Swapping In awesome face operation folder

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
good work!
some improvements needed
-: rename implement face-swapping to just "face-swapping"

-: add some more information in readme such as steps, some research papers or articles about face-swapping from which u took help, what kind of modules u have used

**Comment by ADITYADAS1999** [comment]
> good work! some improvements needed -: rename implement face-swapping to just "face-swapping"
> 
> -: add some more information in readme such as steps, some research papers or articles about face-swapping from which u took help, what kind of modules u have used

okey, i will apply this changes

**Comment by ADITYADAS1999** [comment]
can i close this current pull request and make a new pull request ?

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
still, u haven't changed all your folder names 
image

**Comment by ADITYADAS1999** [comment]
actually i can not change the folder name manually 
So, i remove my folder from my local fork repo and again upload the folder. And want to send a new pull request.

**Pull request closed without merging**
