### PR TITLE
Added Recognition by KNN model.

### PR DESCRIPTION
**Pull request by Aayush-hub**
**Related Issues or bug**
  - Improvement in project by using KNearest Neighbors ML model. It also supports detecting multiple faces.

Fixes: #1 ANY IMPROVEMENTS IN MY PROJECT?
Fixes: #2 CAN WE MAKE IT TO DETECT MULTIPLE FACES?

# Proposed Changes
 - Added KNN model in the project which improves efficiency and accuracy of project. It also supports detecting multiple faces at a time and can collect data for model training in real-time and can also take pre-processed data.
 - `Pre_processed_data_collection.py` takes pre-proceesed images which should be of 640x480 pixels and its axis should be same to train model.The user should provide more than 5 images to train model efficiently.
 - `live_data_collection.py` is to collect live data samples using webcam.
 - `image_recogniser.py` is for recognising images using webcam.
  
# Screenshots
Capture1

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
can you please add a proper readme file along with the pull request so that it will be easy to understand which file we have to run first and what will be the output in the readme file please add some screenshots of output also.

**Comment by Aayush-hub** [comment]
@akshitagupta15june  Sure:)

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Yes great in that readme please write the procedure and implementation
You can have a look at readme of different algos

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
You are a nwoc participant right?

**Comment by Aayush-hub** [comment]
@akshitagupta15june yes mam!

**Comment by akshitagupta15june** [comment]
Awesome work

**Comment by Aayush-hub** [comment]
@akshitagupta15june  Thank you mam:)

**Comment by akshitagupta15june** [comment]
So your points updation will be like this
For solving 2 issue 2+2+1=5
Creating a pr with feature enhancement 15
In total 20 points will be added

**Comment by akshitagupta15june** [comment]
Acc to nwoc guidelines
Let me know if i have missed something

**Comment by Aayush-hub** [comment]
@akshitagupta15june It's all fine mam and thanks for consideration, had a great learning experience with this project and looking forward for more contributions:)

**Comment by akshitagupta15june** [comment]
Hey i can't find your name in contributor spreadsheet
Can you please ask in gitter channel.
Like how should i update your points?

**Comment by Aayush-hub** [comment]
@akshitagupta15june Sure mam, will let you know soon!

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam my name.txt file is not merged in contributors folder yet.

**Comment by Aayush-hub** [comment]
@akshitagupta15june And will I get 10 points for solving a issue labelled intermediate, as the issue #1 Improvement in your project was labelled intermediate.

**Comment by akshitagupta15june** [comment]
> @akshitagupta15june Mam my name.txt file is not merged in contributors folder yet.

I have merged it check in contribution.md

**Comment by akshitagupta15june** [comment]
@Aayush-hub sorry i made a mistake you solved 2 issue one intermediate and one hard
So your points will be 15+10 +5(2 issue)+2(bug report)=32

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam my name.txt is not yet merged in NWOC 's  contributors.md so it is not showing my name in spreadsheet there. Can you help for this?

**Comment by akshitagupta15june** [comment]
Yeah so u have to ask organizers

**Comment by akshitagupta15june** [comment]
To merge it

**Comment by Aayush-hub** [comment]
@akshitagupta15june Okay mam

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam my `name.txt` [Aayush-hub.txt]  is merged in NJAC's contributors.md, so please update my points there. Thank you.

**Comment by akshitagupta15june** [comment]
Ok @Aayush-hub

**Comment by akshitagupta15june** [comment]
Done

**Pull request merged**
