### PR TITLE
Adding feature: IRIS Recognition

### PR DESCRIPTION
**Pull request by sayan9112**
feature request link: https://github.com/akshitagupta15june/Face-X/issues/422

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
Great implementation

**Comment by akshitagupta15june** [comment]
can you make changes in folder name its like you have made two same name folders

**Comment by akshitagupta15june** [comment]
create in a single folder

**Comment by sayan9112** [comment]
> create in a single folder

@akshitagupta15june It is merged now, so I guess making a single file now is not possible.
If you can, please do the needful.

**Comment by sayan9112** [comment]
can you please give me the direct link of my pull request which i can add to my resume. I can not find it.

**Pull request merged**
