### PR TITLE
Tried to make the code simpler 

### PR DESCRIPTION
**Pull request by sudipg4112001**
# Related Issue or bug
  - Info about Issue or bug

Fixes: #236 

# Proposed Changes
 Removed `from google.colab.patches import cv2_imshow`, removed `from skimage import io`, included the write action
 
# Additional info
Replace the image filenames while testing the code, incase the filenames doesn't matches with the desired image filename.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Approving this and will merge after 8

**Review by akshitagupta15june — APPROVED** [review]

**Comment by sudipg4112001** [comment]
Okay..!!

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
There should be two pr
As you solved different issue and both have different points

**Comment by sudipg4112001** [comment]
Okay..!!

**Comment by sudipg4112001** [comment]
Fixes #241 
Added the Face-Swapping file

**Comment by sudipg4112001** [comment]
This PR fixes both #241 and #236

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hi @sudipg4112001 your pr looks great
Can you make some improvements like create an image folder in face-swapping and put all your images there
the second thing for face swapping can you add more information about your implementation in the readme like how you have performed and what steps were there.

**Comment by sudipg4112001** [comment]
Sure

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
hi the image in the face-swapping sample readme is not visible.

**Comment by sudipg4112001** [comment]
> hi the image in the face-swapping sample readme is not visible.

I am working on it.. please wait

**Comment by sudipg4112001** [comment]
Hey, I think all the changes made are proper. Please, review and give me a update.

**Review by akshitagupta15june — APPROVED** [review]
Great @sudipg4112001

**Pull request merged**
