### PR TITLE
A new project Addition 'Real and Fake Face Detection Using Transfer Learning Models'

### PR DESCRIPTION
**Pull request by kanishkakataria**
# Related Issues or bug
  - A whole new project on 'Real and Fake Face Detection' is created using transfer learning algorithms like MobilenetV2,InceptionV3,Xception,VGG16 

Fixes: #1536 

# Proposed Changes
 - A whole new project on 'Real and Fake Face Detection' is created using transfer learning algorithms like MobilenetV2,InceptionV3,Xception,VGG16 .Baseline models along with modifications with dropout,dense and conv2D layers is done to create new models.
# Additional Info
  - Anything related Issues 
  
# Screenshots

Fresh work,completely new 
Screenshots of confusion matrix,accuracy and loss curve are present in readme of each model separately

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Add your implementation inside awesome face operations folder

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Also add output screenshots in the readme and also how to run this implementation then also add references

**Comment by kanishkakataria** [comment]
@akshitagupta15june I have added he changes you suggested in the Real and Fake Face Detection project Readme and have also added the whole project in awesome face operations. I request you to please see it and suggest me with further changes if any .Thank you.

**Review by akshitagupta15june — APPROVED** [review]
Good work!

**Pull request merged**
