### PR TITLE
Added code for Pencil Sketch using OpenCV

### PR DESCRIPTION
**Pull request by iaditichine**
I have added code for Pencil Sketch using OpenCV ( issue number-342) successfully .

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Can you add some sample output images tested on some celebrity images in readme.

**Comment by iaditichine** [comment]
Sure.

**Comment by iaditichine** [comment]
Can I add a readme.doc file because I'm not able to add output images in a text file

**Comment by akshitagupta15june** [comment]
it should be readme.md file

**Comment by iaditichine** [comment]
Okay.

**Comment by akshitagupta15june** [comment]
Make changes and let me know

**Comment by iaditichine** [comment]
Sure. I will do the required changes today itself.

**Pull request closed without merging**
