### PR TITLE
Gssoc issue1

### PR DESCRIPTION
**Pull request by sarah-nisar**
# Readme Improvement in awesome face operations folder #922

Updated the Readme to make it more readable and concise.

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
I think you misunderstood this issue, this issue was about this readme https://github.com/akshitagupta15june/Face-X/blob/master/Awesome-face-operations/Readme.md

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
You have done good work but can you also look at the issue in the readme that some images are not visible in the main readme

image

image


image

**Comment by sarah-nisar** [comment]
I have added the requested changes

**Review by akshitagupta15june — APPROVED** [review]
Good work!

**Pull request merged**
