### PR TITLE
update readme.md

### PR DESCRIPTION
**Pull request by devanshi-code**
# Related Issues or bug
  - Info about Issue or bug

Fixes: #[issue number that will be closed through this PR]

# Proposed Changes
 - Info about changes Goes here
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot **|

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Which readme you have changed, in issue i asked the awesome face operations readme, the folder

**Comment by akshitagupta15june** [comment]
I mentioned the link too

**Comment by devanshi-code** [comment]
Sorry I thought it was about original readme.md, I will update that till tommorow

**Comment by akshitagupta15june** [comment]
No problem it's ok i will review this pr too and will assign point according to the sceme

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
