### PR TITLE
Recognition using efficientnet_b0

### LINKED ISSUE #34: Face Recognition using EfficientNetB0
@akshitagupta15june Can I work on this

### PR DESCRIPTION
**Pull request by Halix267**
closes #34

### CODE REVIEW

**Comment by Halix267** [comment]
@akshitagupta15june Plzz review

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Great work @Halix267

**Comment by akshitagupta15june** [comment]
Will be updating your points by today.

**Comment by Halix267** [comment]
Ok no problem @akshitagupta15june

**Comment by akshitagupta15june** [comment]
I have updated your points please check

**Pull request merged**
