### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by bcsamrudh**
Fixes: [#1356](https://github.com/akshitagupta15june/Face-X/issues/1356)

# Proposed Changes
 Updated the README.md File to have more information about project.
Added a Demostration Image
 
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
original|after_changes

### CODE REVIEW

**Comment by bcsamrudh** [comment]
Should I also add a demostration Image!

**Comment by akshitagupta15june** [comment]
> Should I also add a demostration Image!

yes u should add

**Comment by bcsamrudh** [comment]
Should it be a video.

**Comment by akshitagupta15june** [comment]
no an image will be better

**Comment by bcsamrudh** [comment]
ok

**Comment by bcsamrudh** [comment]
I have added an Image.

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Great!

**Comment by bcsamrudh** [comment]
Thank you

> Great!

**Pull request merged**
