### PR TITLE
Add Face Recognition using Inception-Resnet-v2 for #949

### PR DESCRIPTION
**Pull request by suvadityamuk**
Added a complete from-scratch implementation of the Inception-Resnet-v2 model in Pytorch (by Szegedy et. al.) with a custom dataset implementation of the CelebA dataset to go with it, as well as some preliminary data information, all bundled up in the Jupyter notebook. Solves #949 

Signed-off-by: Suvaditya Mukherjee <suvadityamuk@gmail.com>

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hey, @suvadityamuk it's great that you have implemented this issue, please add proper documentation containing the steps, modules you have used, how to run it, as well as output screenshots.
You can take help from other readme present in face-x repo

**Comment by suvadityamuk** [comment]
> Hey, @suvadityamuk it's great that you have implemented this issue, please add proper documentation containing the steps, modules you have used, how to run it, as well as output screenshots. You can take help from other readme present in face-x repo

Please check the latest commit and let me know if that is fine. I hope this is sufficient for the explanations needed. Output images could not be attached since I do not have model-training resources

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
everything is fine @suvadityamuk but still the readme is not there describing what you implemented.. Have a look at this implementation https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-Algorithms/Recognition%20Using%20MobileNetV2 , you can see how the readme are formed

**Comment by suvadityamuk** [comment]
I can make a simple readme and attach it, but I won't be able to break it down as given in that example, since in my case, the model is not trained and any user willing to use it will have to train it before performing any task. How to train and other such things are already mentioned in the notebook itself. What to do in that case?

**Comment by akshitagupta15june** [comment]
> I can make a simple readme and attach it, but I won't be able to break it down as given in that example, since in my case, the model is not trained and any user willing to use it will have to train it before performing any task. How to train and other such things are already mentioned in the notebook itself. What to do in that case?

ok so make a readme and also mention that your model is not trained also you can create a issue so that if any other want to work they can

**Comment by suvadityamuk** [comment]
Please do check and let me know if this is fine @akshitagupta15june

**Review by akshitagupta15june — APPROVED** [review]
Good work @suvadityamuk! Merging your pr

**Pull request merged**
