### PR TITLE
Added pic makeover.

### PR DESCRIPTION
**Pull request by Aayush-hub**
# Related Issuse or bug
  - Virtual Makeover of a face by facial landmark detection and 

Fixes: #68 Virtual Makeover of a face by facial landmark detection.
# Proposed Changes
 - Added Virtual makeover using dlib and opencv. It supports both real time frame and pre-clicked image, even user can click picture and can use it to make changes.
 # Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
img | |
img|

### CODE REVIEW

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam, Please my review my PR as a SWOC2021 participant:)

**Comment by akshitagupta15june** [comment]
hi there is no filter

**Comment by akshitagupta15june** [comment]
snapchat filters are different

**Comment by Aayush-hub** [comment]
@akshitagupta15june Okay Mam, Sorry for that. Can I know is my PR solving isuue no. #68 ?

**Comment by Aayush-hub** [comment]
@akshitagupta15june Sorry mam, for the inconveniencecaused my me, will update my PR:)

**Pull request closed without merging**
