### PR TITLE
Added New Snapchat Filter using OpenCV and MediaPipe (Dragon flame and funny eyeballs)

### PR DESCRIPTION
**Pull request by pra9patil**
Hi @akshitagupta15june 

I hope you're doing well! I wanted to let you know that I've made some changes to the project by adding a new Snapchat filter using OpenCV and MediaPipe. This filter brings an exciting and interactive element to the live video feed.

Here's a summary of the changes:

- Implemented a new filter 
- Utilized OpenCV and MediaPipe libraries for real-time face detection, facial landmarks detection, and image processing.
- Added the necessary dependencies to the `requirements.txt` file for easy installation.
- Documented the usage instructions and other relevant details in the README file.

I believe that this new addition enhances the overall user experience and adds more value to the project. I have thoroughly tested the changes to ensure they work as expected.

Please review the pull request at your convenience. I'm open to any feedback or suggestions you may have. I'm excited to contribute to the project and be a part of its growth.

Thank you for your time and consideration!

Best regards,
Pranav

### CODE REVIEW

**Comment by pra9patil** [comment]
#1504

**Review by Codingpanda252 — COMMENTED** [review]
This project has been copied exactly from https://bleedaiacademy.com/facial-landmark-detection-with-mediapipe-creating-animated-snapchat-filters/

**Comment by Inferno2211** [comment]
This seems to be copied from this vid: https://www.youtube.com/watch?v=QERl1-ckFr8
Blogpost from the same author: https://bleedaiacademy.com/facial-landmark-detection-with-mediapipe-creating-animated-snapchat-filters/

**Comment by pra9patil** [comment]
Bro this not copied I learn it and then implemented, so don't call it as copied

**Comment by pra9patil** [comment]
@akshitagupta15june ma'am you can check that blog contains jupyter note book that proves that , this is not just copy pasting , I my self type and learn this project ,  as you say in introduction session you can refer youtube videos .
give your feedback ma'am

**Comment by akshitagupta15june** [comment]
Hey! First of all when I told to take help from tutorials it doesn't means to directly copy everything, it like for understanding purposes you can check them, you should have taken help from the tutorial but tried to create something new or added some features to it.
That's why I hope you will learn from this and I will be waiting for your new and creative implementation.
Closing this pr.
Thankyou
Akshita

**Pull request closed without merging**
