### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by Code1705**
# Related Issues or bug
  - Info about Issue or bug

Fixes: #[issue number that will be closed through this PR]

# Proposed Changes
 - Info about changes Goes here
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot **|

### CODE REVIEW

**Comment by Code1705** [comment]
made changes , please  could you merge it?

**Comment by Code1705** [comment]
#1334  issue solved  ,please merge my pr?

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Please remove that chrome extension thing 
It's not a chrome extension and also do not add back to app everywhere just 3 time is sufficient

**Comment by Code1705** [comment]
now is it ok?

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
good work!

**Pull request merged**
