### PR TITLE
Recognition using Vgg 19

### LINKED ISSUE #19: Face Recognition using VGG-19
@akshitagupta15june Can I work on this

### PR DESCRIPTION
**Pull request by Halix267**
closes #19

### CODE REVIEW

**Comment by Halix267** [comment]
@akshitagupta15june Plzz review.

**Comment by akshitagupta15june** [comment]
Can you please add a readme file showing procedure as well as outputs
It will be great.

**Comment by Halix267** [comment]
@akshitagupta15june in readme i will add only procedure to run , but what kind of output u want ?

**Comment by Halix267** [comment]
i mean u want me add the output in the readme which i have send u in the respective pr ??

**Comment by akshitagupta15june** [comment]
Yes the output which u have send in each pr

**Comment by Halix267** [comment]
Ok

**Comment by Halix267** [comment]
@akshitagupta15june Plzz review I have made the changes

**Comment by akshitagupta15june** [comment]
Great

**Comment by akshitagupta15june** [comment]
Will be updating your points +20

**Comment by Halix267** [comment]
and Extra 2 points for opening issue ?? :)

**Comment by akshitagupta15june** [comment]
See how 20 I am giving 15 is solving hard or and 5 I am giving which contains 2 points for solving issue and 3 extra is because this is enhancement in project

**Comment by akshitagupta15june** [comment]
So it is 15+2+3

**Comment by akshitagupta15june** [comment]
3 points are already extra for you and this is only in these or because these are good prs

**Comment by akshitagupta15june** [comment]
I hope you got it @Halix267

**Comment by Halix267** [comment]
Ohh sorry sorry ,  I thought hard issue has 20 points :)

**Comment by akshitagupta15june** [comment]
Your points are now 125 please check and let me know

**Comment by Halix267** [comment]
Yes it is updated , Thanks a lot @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Following nwoc 15-hard issue 10 intermediate and 5 easy

**Comment by akshitagupta15june** [comment]
> Yes it is updated , Thanks a lot @akshitagupta15june
No problem keep going

**Comment by Halix267** [comment]
Also one query @akshitagupta15june  , When i am dowloading the mobilenet model fromm keras It is giving me error, It strats the downloading procedure but at last it gives error , How can I resolve it??

**Pull request merged**
