### PR TITLE
Snapchat Filters using OpenCV #66

### PR DESCRIPTION
**Pull request by hemanthraj2001**
# Related Issues or bug
  - Added a Shiva Tilak Snapchat Filter

Fixes: #66 

# Proposed Changes
 - added a new filter

 
# Additional Info
  - Added another new snap filter using OpenCV
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 
family
 | 
family with fliter
 |

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
@hemanthraj2001   can you please mention the open-source program in which you are participating?

**Comment by hemanthraj2001** [comment]
> 

Codepeak

**Comment by akshitagupta15june** [comment]
ok

**Review by akshitagupta15june — APPROVED** [review]
Awesome Work!
Cool Filter
Merged

**Pull request merged**
