### PR TITLE
Added Let'sGrowMore logo issue#909

### PR DESCRIPTION
**Pull request by Ayan-thecodeking**
# Related Issues or bug
  - Info about Issue or bug

Fixes: #909 

# Proposed Changes
 Added Let'sGrowMore logo  under 'Open Source Program' section readme 

do review my PR @akshitagupta15june  
thanks :)

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Keep it inside engaging and collaborating like other programs are there

**Comment by Ayan-thecodeking** [comment]
> Keep it inside engaging and collaborating like other programs are there

Ok got it @akshitagupta15june

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
can you make the logo small as all other logo are there align it according to other logo

**Comment by Ayan-thecodeking** [comment]
> can you make the logo small as all other logo are there align it according to other logo

Ok I'll do it today

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
.

**Comment by Ayan-thecodeking** [comment]
> .

Sry due to my assignment I was unable to update it ...give some more time I'll do that for sure

**Comment by akshitagupta15june** [comment]
no problem you can take time!

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
closing this

**Pull request closed without merging**
