### PR TITLE
Add Pencil Sketch in Python using OpenCV Readme File Update 

### PR DESCRIPTION
**Pull request by Vi1234sh12**
# Related Issuse or bug
  - Readme Improvement in pencil sketch (https://github.com/akshitagupta15june/Face-X/issues/388)

# Proposed Changes
 - Info about changes Goes here
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
Cap1
 | Cap|

### CODE REVIEW

**Comment by Vi1234sh12** [comment]
Update Readme File: Pencil Sketch Project

**Comment by Vi1234sh12** [comment]
Screenshot (649)

Hello Everyone! Actually, I'm Facing one problem Anyone can you solve this 
error message : "Resource not accessible by integration"

**Review by akshitagupta15june — APPROVED** [review]
Great @Vi1234sh12

**Comment by Vi1234sh12** [comment]
> Great @Vi1234sh12

Thank you so much

**Pull request merged**
