### PR TITLE
Real time age detector

### PR DESCRIPTION
**Pull request by ahmed-cyber**
# Related Issuse or bug
  - Info about Issue or bug

Fixes: #[issue number that will be closed through this PR]

# Proposed Changes
 - Info about changes Goes here
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot **|

### CODE REVIEW

**Comment by ahmed-cyber** [comment]
@akshitagupta15june  review my PR please

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Can you please add a proper readme showing your implementation along with an output screenshot in that readme?

**Comment by ahmed-cyber** [comment]
readme file has been added

**Review by akshitagupta15june — APPROVED** [review]
Great work @ahmed-cyber

**Pull request merged**
