### PR TITLE
Google colab module removed, and detailing added

### PR DESCRIPTION
**Pull request by sudipg4112001**
Google colab module is removed and simpler OpenCV framework is used. Captions will be displayed along with the image.

# Related Issuse or bug
 Google colab module is specifically used for working in the same, and detailing of the images was missing during display.

Fixes: #411

# Proposed Changes
 I have omitted the google collab module and added some captions in each display part.

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hi this not allowed to change anything without prior issue.

**Comment by sudipg4112001** [comment]
I will raise a issue, then I can change ?

**Comment by akshitagupta15june** [comment]
@sudipg4112001 yes you can create a issue.
are you dwoc participant?

**Comment by sudipg4112001** [comment]
Ok..!
I am a participant of GSSOC 2021

**Comment by akshitagupta15june** [comment]
hi please wait till the coding period starts

**Comment by sudipg4112001** [comment]
> Ok..!
> I am a participant of GSSOC 2021

I am also a participant of CWOC.

**Comment by sudipg4112001** [comment]
This project is available for this program also.

**Pull request closed without merging**
