### PR TITLE
Uploaded the ensemble facial recognition

### PR DESCRIPTION
**Pull request by Adarsh88**

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
can you add in this implementation inside face recognition folder.

**Comment by Adarsh88** [comment]
Please check it now @akshitagupta15june. I am a participant of SWOC not JWOC.

**Comment by akshitagupta15june** [comment]
ok can you add it in recognition-algoritjm folder

**Comment by akshitagupta15june** [comment]
here https://github.com/akshitagupta15june/Face-X/tree/master/Recognition-Algorithms

**Comment by Adarsh88** [comment]
Done

**Review by akshitagupta15june — APPROVED** [review]
Great @Adarsh88

**Comment by Adarsh88** [comment]
Thanks @akshitagupta15june 😊

**Pull request merged**
