### PR TITLE
Added filters and GUI for filters.

### PR DESCRIPTION
**Pull request by Aayush-hub**
# Related Issuse or bug
  - Added GUI for Snapchats Filter in a face image with image capture functionality.
  - Added Snapchat Filters using OpenCV

Fixes: #67  GUI for Snapchats Filter in a face image
Fixes: #66 Snapchat Filters using OpenCV

# Screenshots
Capture

# GUI
Capture1

### CODE REVIEW

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam please review my PR for SWOC.

**Comment by akshitagupta15june** [comment]
Hi many files have changed it will take time.
My end sem are going on so it will be delayed.

**Comment by Aayush-hub** [comment]
@akshitagupta15june Mam can you please review and approve for now?, Otherwise no problem.

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Great work @Aayush-hub

**Pull request merged**
