### PR TITLE
New Snap Chat _swirlyfilter

### PR DESCRIPTION
**Pull request by sahaycodes**
# Created a New SnapChat Filter - Swirly Glasses

Fixes: #1421 

# Proposed Changes
 - A new addition to the snap chat filters of this repo
 
# Additional Info
  - Used - Python Language, OpenCV
  - Haar Cascade Classifier 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
   
                                 
swirlyop

                              

 **original screenshot** | **updated screenshot **|

### CODE REVIEW

**Review by 072arushi — CHANGES_REQUESTED** [review]
Please add comments to explain your code, And you need to explain the changes made in the description as well

**Comment by sahaycodes** [comment]
created a new and basic snapchat filter. 
It adds a swirly glass on the face of the user. 
Used OpenCV and Haar Cascade Classifier for the filter.

For Code -
1. importing the necessary libs and the filters' png file 
2. loading the haarcascade classifier file for frontal face region
3. reading the video stream
4. converting the frame to grayscale
5. applying it on the facial region by transparent overlay 
6. displaying the resultant frame.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
can u please add a readme file explaining all your code and how to run ur code
take reference from snapchat_filter folder

**Comment by sahaycodes** [comment]
Have added the ReadMe.md for the code

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
https://github.com/akshitagupta15june/Face-X/tree/master/Snapchat_Filters please add your implementation inside this folder and also rename nesnapchatfilter to swirlyfilter

**Comment by sahaycodes** [comment]
added the swirly filter files in the Snapchat_Filter folder.

**Comment by sahaycodes** [comment]
do I directly add the contents in the Snapchat folder of this repo or wait for this PR to be merged.

**Review by akshitagupta15june — APPROVED** [review]

**Comment by Raksha703** [comment]
Hey, I am SSOC'23 contributer and want to work on this issue. Pleases assign it to me.

**Comment by 072arushi** [comment]
@Raksha703 assigned

**Comment by Raksha703** [comment]
added a file. Please check!

**Pull request merged**
