### PR TITLE
Recognition using mobile net v2

### LINKED ISSUE #23: Recognition using MobileNetV2
@akshitagupta15june Can I work on this??

### PR DESCRIPTION
**Pull request by Halix267**
closes #23 

@akshitagupta15june Plzz review it.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Great work @Halix267  can you please also add some outputs which you are getting in readme file.

**Comment by Halix267** [comment]
ok wait

**Comment by Halix267** [comment]
@akshitagupta15june done

**Comment by akshitagupta15june** [comment]
Well done !
Will be updating your points.

**Comment by akshitagupta15june** [comment]
@Halix267 please check your points have been updated

**Comment by Halix267** [comment]
Yes @akshitagupta15june  thanks

**Comment by Halix267** [comment]
@akshitagupta15june Can u guide me lane detection issue

**Comment by Halix267** [comment]
I am facing some troubles

**Comment by akshitagupta15june** [comment]
What type of issue
Can you elaborate?

**Pull request merged**
