### PR TITLE
FaceX Library V1.0

### PR DESCRIPTION
**Pull request by AdityaNikhil**
Follow the **pending tasks** section in this [issue](https://github.com/akshitagupta15june/Face-X/issues/312) to track the status of this library,

Added following algorithms in the library with a readme,
1) Face detection
2) Cartoonify 
3) Background blur

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hi this readme is not neded

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
you should have mentioned the issue what you have solved not everything in the single pr

**Comment by AdityaNikhil** [comment]
@akshitagupta15june  Please check this [issue](https://github.com/akshitagupta15june/Face-X/issues/312). I've mentioned few tasks under **pending tasks** section there. This PR follows up by more upcoming PRs but won't close any single issue.

**Comment by akshitagupta15june** [comment]
Got it merging your pr great @AdityaNikhil

**Pull request merged**
