### PR TITLE
Added a GUI for face recognistion using LBPH algo

### PR DESCRIPTION
**Pull request by saiharsha-22**
Fixes: #87 

# Proposed Changes
 - GUI for LBPH algo 
  
# Screenshots
Screenshot (121)

### CODE REVIEW

**Comment by saiharsha-22** [comment]
@akshitagupta15june solved issue #87

**Comment by saiharsha-22** [comment]
@akshitagupta15june  one small doubt, The actual contribution will start from today right? for swoc 2021, according to the website.

**Comment by akshitagupta15june** [comment]
Yes

**Comment by akshitagupta15june** [comment]
Your pe is merged 
Great work!

**Pull request merged**
