### PR TITLE
Real-Time Liveness Based Face Recognition System 

### PR DESCRIPTION
**Pull request by smriti1313**
# Related Issuse or bug
  - Real-Time Liveness Based Face Recognition System 

Fixes: #200 

# Proposed Changes
 - Added trained models so as they can detect between a fake/spoofed face and real face.
 
# Additional Info
  - Read [here](https://github.com/smriti1313/Face-X/tree/facial-recognition/Real-Time%20Liveness%20Based%20Face%20Recognition%20System)

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
please put all your implementation inside this folder https://github.com/akshitagupta15june/Face-X/tree/master/Realtime-liveness-recognition-system

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
https://github.com/akshitagupta15june/Face-X/tree/master/Realtime-liveness-recognition-system

**Comment by smriti1313** [comment]
> please put all your implementation inside this folder https://github.com/akshitagupta15june/Face-X/tree/master/Realtime-liveness-recognition-system

I am not sure but if you merge the PR then won't the changes will be reflected in your master branch?

**Comment by akshitagupta15june** [comment]
i havent merge til;l now whatever the changes you will make it will be reflected.

**Comment by smriti1313** [comment]
> 
> https://github.com/akshitagupta15june/Face-X/tree/master/Realtime-liveness-recognition-system

I will generate a new PR since uploading directly in the above link is prohibited.

**Pull request closed without merging**
