### PR TITLE
Facial Recognition Attendance Management System 

### PR DESCRIPTION
**Pull request by smriti1313**
# Related Issuse or bug
  - Facial Recognition Attendance Management System 

Fixes: #48

# Proposed Changes
 - added Facial Recognition Attendance Management System

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hi very great work! Can you add a gif or some images in readme file showing how will this project actually look after working like what will be the GUI

**Comment by smriti1313** [comment]
> 
> 
> Hi very great work! Can you add a gif or some images in readme file showing how will this project actually look after working like what will be the GUI

Can you check the face-x channel on discord please?

**Comment by akshitagupta15june** [comment]
yes i have checked what i can add!

**Comment by akshitagupta15june** [comment]
can you please update readme with gui pic or working gif.?

**Comment by akshitagupta15june** [comment]
I am looking on it

**Comment by akshitagupta15june** [comment]
Are u a swoc participant?

**Comment by smriti1313** [comment]
> Are u a swoc participant?

no. I am a dwoc participant.

**Review by akshitagupta15june — COMMENTED** [review]
You pr is in review status

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
