### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SoyabulIslamLincoln**
# Related Issuse or bug
  - Creation of a GUI that cartoonifies image and save it

Fixes: #57 

# Proposed Changes
 - More Interactivity on GUI
 
# Additional Info
  - Can add slidebars or buttons to change the parameters

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
can you please add the picture of gui like how is it working or a gif showing the procedure in readme file.

**Comment by SoyabulIslamLincoln** [comment]
Yes ma'am. Sure.

**Comment by SoyabulIslamLincoln** [comment]
I actually added a screen video in the read me file. But that's is not seeing here. I am solving the issue right away.

**Comment by SoyabulIslamLincoln** [comment]
Ma'am I have resolved the issue. Would you check it and tell me if everything is okay?

**Comment by akshitagupta15june** [comment]
Hi the picture is kinda not visible but can you please let me know like what buttons you have added in the gui and a clear picture of it

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
the gui interface not visible.

**Review by SoyabulIslamLincoln — COMMENTED** [review]
Hi @akshitagupta15june . I wish everything is now visible.

**Review by akshitagupta15june — APPROVED** [review]
Ok great ! will be merging your pr.

**Comment by akshitagupta15june** [comment]
@SoyabulIslamLincoln are you a dwoc or swoc participant?

**Comment by SoyabulIslamLincoln** [comment]
I am a dwoc participant.

**Comment by akshitagupta15june** [comment]
ok i am merging the pr.
good work!

**Comment by SoyabulIslamLincoln** [comment]
Thanks a lot @akshitagupta15june . in the GUI i think it is possible to add parameters so that user can change their photo as they want. I am a beginner in here. But you can create an issue so that other participants can work on that. Thank you very much for your support and direction.

**Comment by akshitagupta15june** [comment]
sure i will create one.

**Pull request merged**
