### PR TITLE
New_Filter = Added (Christmas + Halloween) together 

### PR DESCRIPTION
**Pull request by PiyushDhirwani**
# New feature
  - Filter add

added: #932

# About
 - I used the cv2 OpenCV library to implement the filters
 - Defined function to set up the filters
  
# Screenshots

 input           | output with filter
 :--------------------: |:--------------------:
 **WIN_20211207_13_35_00_Pro** | **Happy(christmas+halloween) **|

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
@Komal-99 will review it after the buffer period!

**Comment by PiyushDhirwani** [comment]
From codepeak

**Comment by akshitagupta15june** [comment]
ok

**Review by akshitagupta15june — APPROVED** [review]
Awesome Work!
Cool Filter

**Comment by PiyushDhirwani** [comment]
Thanks

**Pull request merged**
