### PR TITLE
added the pig nose snapchat filter for #66

### PR DESCRIPTION
**Pull request by koolgax99**
# Related Issuse or bug
  - Adding the snapchat filter

Fixes: #66 

# Proposed Changes
 - This filter adds the pig nose at the place of the actual nose. 
  
# Screenshots
pig_nose

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
please add a readme file with all process description and an output showing this filter on face

**Comment by koolgax99** [comment]
#85 

The  process:
- Using the OpenCV detecting the face in the face
- For every Face I had to detect the landmarks on the face using the 68 facial landmark coordinates
- Using the coordinates I had to detect the coordinates 29(top_nose), 30(center_nose), 31(left_nose) and 35(right_nose)
- After detecting the coordinates, reduce the size of the pig_nose into that area
- and then mask the pig_nose into the actual frame

The Facial Landmark Coordinates
facemarks points

The screenshot with the filter

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
awesome @koolgax99

**Comment by akshitagupta15june** [comment]
are you a dwoc or nwoc or swoc participant?

**Comment by koolgax99** [comment]
Thankyou @akshitagupta15june . I am a DWoC participant.

**Comment by akshitagupta15june** [comment]
ok i am merging your pr

**Comment by koolgax99** [comment]
Thankyou for your guidance. Also can we add more filters to it? 

Are there any other projects and issues I can be a part of?

**Comment by akshitagupta15june** [comment]
ofcourse you can add i have reopened the issues.
yes the projects in my readme open for collaboration.

**Pull request merged**
