### PR TITLE
Gca - Gender Classification API

### PR DESCRIPTION
**Pull request by CrispenGari**
Fixes: #1332

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Wonderful implementation
Thanks for your contributions

Can you add all your implementation folder inside facex Library folder which is available in repo

**Comment by CrispenGari** [comment]
Thanks for your feedback. Which implementation folder are you talking about, i'm a little bit lost because everything that is needed to run the API is here!

**Comment by akshitagupta15june** [comment]
I am talking about the folder in repo named facex Library

**Comment by CrispenGari** [comment]
Done!!

**Review by akshitagupta15june — APPROVED** [review]
Perfect 👍
Again thanks for contribution

**Comment by akshitagupta15june** [comment]
Don't forget to add your name in contributors.md

**Comment by akshitagupta15june** [comment]
Are you a SWOC participant?

**Comment by CrispenGari** [comment]
No i’m not @akshitagupta15june .

**Pull request merged**
