### PR TITLE
ADDED A CUSTOM CNN MODEL FOR FACIAL EXPRESSION RECOGNITION

### PR DESCRIPTION
**Pull request by Rishi-11-2**
A CUSTOM CNN MODEL FOR FACIAL EXPRESSION RECOGNITION

Trained on FER-2013 Dataset.

Model was not included as it was large in size

### CODE REVIEW

**Comment by Rishi-11-2** [comment]
ISSUE #1436

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Add a proper readme to this implemetation like adding screenshots of output, how to run this

**Review by 072arushi — APPROVED** [review]

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
provide a proper readme

**Comment by akshitagupta15june** [comment]
no response received, hence closing

**Pull request closed without merging**
