### PR TITLE
created Cartoonify

### PR DESCRIPTION
**Pull request by dilroseR**
Fixes: #923 

conversion of images into cartoon through gaussian filter

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
great

**Comment by dilroseR** [comment]
> great

Can i get the google form link here so that I can fill that the PR is merged?

**Comment by akshitagupta15june** [comment]
are you a devincept participant?

**Comment by dilroseR** [comment]
> are you a devincept participant?

yes

**Comment by akshitagupta15june** [comment]
https://forms.gle/Juja4kpNcMjg6t5X8 please fill this

**Pull request merged**
