### PR TITLE
Face Detection using Haar Cascade

### PR DESCRIPTION
**Pull request by srimontidutta**
@akshitagupta15june Added the model for Face Detection using Haar Cascade.
Section- Face Detection (Issue-89)
Please check it.

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Can you add a proper readme and the mention issue number which you have solved?

**Comment by srimontidutta** [comment]
> Can you add a proper readme and the mention issue number which you have solved?

Yes, please check it.

**Comment by akshitagupta15june** [comment]
your pull request will be reviewed by mentor @mayank8200

**Comment by srimontidutta** [comment]
> your pull request will be reviewed by mentor @mayank8200

Okay, thanks!

**Comment by akshitagupta15june** [comment]
please add a readme file @srimontidutta

**Comment by srimontidutta** [comment]
> please add a readme file @srimontidutta

On Haar Cascade?
Also, in a separate PR containing only the readme or the code files as well?

**Pull request merged**
