### PR TITLE
DeepFake Generation

### PR DESCRIPTION
**Pull request by Soubeer**
# Related Issues or bug
  Added folder separately for DeepFake Generation.
 

Fixes: #[1772]

# Proposed Changes
 -Any dataset can be used just by adding it to the file and running it to create new structures.
 Works faster compared to Traditional models because of Generative Adversarial Network.
 
# Additional Info
  -I checked the Contributors doc..should I include my name there or will it be updated later on?
  
# Screenshots

image
Scores of the final Output

image
Losses from GAN

### CODE REVIEW

**Comment by sanjay-kv** [comment]
@akshitagupta15june  could you look into it.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
please mention proper readme and these kind of ipynb will not be accepted also with implementation screenshots

**Comment by Soubeer** [comment]
> please mention proper readme and these kind of ipynb will not be accepted also with implementation screenshots

ill add a readme , but for the ipynb , it shows the data for how much accurate it is wrt the real data given. the user can just add or use any dataset to create deepfakes with this notebook.
what changes do i need to make in it?

**Comment by Soubeer** [comment]
@akshitagupta15june i made the changes and the reason for outputs..can you check my PR?

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
please add ur complete implementation inside awesome face operation folder

**Pull request closed without merging**
