### PR TITLE
 algorithm of snapchat filter added.

### PR DESCRIPTION
**Pull request by utkarsh147-del**
I have uploaded the algorithm of detective filter with full detail.

# Related Issuse or bug
  -Add the details of all filter implented algorithm with enhancement

Fixes: #[293]

# Proposed Changes
 - Added the algorithm of Snapchat filter
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot **|

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hi can you correct the readme file because the steps are looking like a paragraph even tags are visible

**Comment by utkarsh147-del** [comment]
Yes I will correct this soon

**Review by utkarsh147-del — COMMENTED** [review]
I have updated the error

**Review by akshitagupta15june — APPROVED** [review]
Great @utkarsh147-del

**Comment by utkarsh147-del** [comment]
So I have updated the algorithm,So can you please merged this pull request?

**Comment by utkarsh147-del** [comment]
Thankyou mam

**Pull request merged**
