### PR TITLE
Update ReadMe #1076

### PR DESCRIPTION
**Pull request by Ank1taS**
# Related Issues or bug
#1076
 

# Proposed Changes
1. Fixed typos
2. Improved markdown for the installation section
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 ### Original           
 
Screenshot_20230108_190232

### Updated

Screenshot_20230108_190155

### CODE REVIEW

**Comment by Solivagant14** [comment]
@Ank1taS The improvement in the markdown for the installation section makes it more confusing. I think it's a good idea not to change it. The typos are good to go.

**Comment by akshitagupta15june** [comment]
thanks for reviewing @Solivagant14 
@Ank1taS please make the changes according to the mentors suggestions

**Review by harshit-paneri — APPROVED** [review]
Changes is approved, You used correct markdown for cmd.✨

**Comment by harshit-paneri** [comment]
Hey @akshitagupta15june This PR is ready for merge✨

**Review by akshitagupta15june — APPROVED** [review]
Thanks for contributing

**Comment by Ank1taS** [comment]
> Changes is approved, You used correct markdown for cmd.✨

Thank you

**Pull request merged**
