### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by anasadh**
I have added my own butterfly filter, which is unique and has not been added before by anyone else.

butterfly_filter

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
Please add a proper readme with output screenshot

**Comment by anasadh** [comment]
> 2 workflows awaiting approval

Sure mam.

**Comment by anasadh** [comment]
> Please add a proper readme with output screenshot

mam I have made a proper readme , kindly look that. and still if there is need to make any change please tell.

**Review by akshitagupta15june — APPROVED** [review]
Please add ur implementation inside the snapchat filters folder

**Comment by anasadh** [comment]
> Please add ur implementation inside the snapchat filters folder

okay mam

**Comment by akshitagupta15june** [comment]
hey i can't see the readme?

**Comment by akshitagupta15june** [comment]
readme contains only this much content # Snapchat-Filter-using-OpenCV

It is a cool butterfly filter.

**Comment by anasadh** [comment]
> readme contains only this much content # Snapchat-Filter-using-OpenCV
> 
> It is a cool butterfly filter.

yes mam it was my previous readme file, last night I changed it but today I replaced it by previous one by mistake, so I am correcting it.

**Comment by anasadh** [comment]
> readme contains only this much content # Snapchat-Filter-using-OpenCV
> 
> It is a cool butterfly filter.

mam now I have changed it ,please look at it.

**Review by akshitagupta15june — APPROVED** [review]
Awesome work 👍 @anasadh

**Comment by anasadh** [comment]
> Awesome work 👍 @anasadh

Thanks a lot mam for your time.😊

**Pull request merged**
