### PR TITLE
Added Ravana filter

### PR DESCRIPTION
**Pull request by Riddhiman-M**
<li>Displays an image with 5 heads each with crowns (based on Ravana).
<li>To save the image, press 's', and press 'x' to exit. (Please press 2-3 times to ensure saving/ exit)

# Related Issues or bug
  - Adding  cool snapchat/ instagram filter for Dussehra

Fixes: #1228 

# Proposed Changes
 - The multi-head feature can be further improvised by using a better face detecting algorithm instead of haarcascades.
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Self | IAmRavana|

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
Wow! That is so good
Well done
Thanks for contributing 💜

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Please add all your implementation folder inside Snapchat filters

**Comment by Riddhiman-M** [comment]
Hi thanks! I've added the implementation files to the Snapchat folder and opened a new pull request.

**Comment by akshitagupta15june** [comment]
I can't see your pr

**Pull request closed without merging**
