### PR TITLE
Created a chef hat filter

### PR DESCRIPTION
**Pull request by Imsachin010**
# Related Issues or bug
  - related to creating snapchat or instagram filter using opencv

Fixes: #[1229]

# Proposed Changes
 - Created a filter by using chef hat in python.
 

  - Anything related Issues

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Add output screenshots in readme

**Comment by akshitagupta15june** [comment]
@Imsachin010

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
Add screenshot in conversation and readme both

**Comment by Imsachin010** [comment]
I'm using arch linux os because of that some of the python libraries weren't supporting, So I got late to submit the same

Cheffilter1

**Review by harshit-paneri — APPROVED** [review]

**Comment by Imsachin010** [comment]
please review my PR @akshitagupta15june

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
I am not getting why you are using tiara code because u have added the output image from Google but here we need what you are getting as output, you should add a proper image how your code is working and how you are getting a chef hat on your head

**Review by 072arushi — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
@Imsachin010 are u working on this?

**Comment by akshitagupta15june** [comment]
@Imsachin010 i am closing this pr as i have received no response till now

**Pull request closed without merging**
