### PR TITLE
Eye-Blink Counter

### PR DESCRIPTION
**Pull request by SatYu26**
# Related Issuse or bug
  - Adding of Eye-Blink Counter in Face-Emotions-Recognition

Fixes: #244

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hi, @SatYu26  can you please improve your readme and add an explanation about what you have done in this enhancement request with the output screenshot.
There is no hurry or of gssoc will be merged after 8

**Comment by SatYu26** [comment]
> Hi, @SatYu26 can you please improve your readme and add an explanation about what you have done in this enhancement request with the output screenshot.
> There is no hurry or of gssoc will be merged after 8
Sure I will be making changes asap.

**Comment by SatYu26** [comment]
@akshitagupta15june should i do any more changes?

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
pictures you have added in readme are not visible

**Comment by SatYu26** [comment]
> pictures you have added in readme are not visible

Yeah I have added then by linking to this repo, so after it is merged they will be visible.

**Comment by akshitagupta15june** [comment]
Hi can you keep all your pictures in a image folder inside the blink-counter folder

**Comment by SatYu26** [comment]
> Hi can you keep all your pictures in a image folder inside the blink-counter folder

yes I did just now.

**Comment by SatYu26** [comment]
> GReat @SatYu26

Thank you @akshitagupta15june

**Pull request merged**
