### PR TITLE
Added EfficientNetB1

### PR DESCRIPTION
**Pull request by infiniteoverflow**
Fixes: #113 

# Proposed Changes
 - I have implemented EfficientNetB1 architecture on Karolinska Directed Emotional Faces (KDEF) dataset. The dataset can be found here : https://www.kdef.se/

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
Hi can you add a proper readme file with explanation of implementation.
Also can you add all you implementation inside recognition folder.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Hi can you add a proper readme file with explanation of implementation.
Also can you add all you implementation inside recognition folder.

**Comment by infiniteoverflow** [comment]
@akshitagupta15june Thank you for the review. I have updated the PR as per the requested changes. Kindly have a look and let me know if any more changes are required ?

**Review by akshitagupta15june — COMMENTED** [review]
Great

**Pull request merged**
