### PR TITLE
added face morph with opencv

### PR DESCRIPTION
**Pull request by suyogkokaje**
# Related Issues or bug
  -Face Morph using opencv

Fixes: #995 

# Proposed Changes
 - I added the Face Morph using opencv.
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot **|

# Photo of Donald Trump
donald-trump

# Photo of Hillary Clinton
hillary-clinton

# Result
Screenshot-1401

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
can you add your folder inside this folder

**Comment by akshitagupta15june** [comment]
are u a codepeak participant or a swoc one?

**Comment by suyogkokaje** [comment]
Can u tell the name of the folder in which I have to add this folder? 😅

**Comment by suyogkokaje** [comment]
> are u a codepeak participant or a swoc one?

I am SWoC participant

**Comment by akshitagupta15june** [comment]
go yo Awesome-face-operations folder search for face-morphing folder nad add your folder inside the face morphing

**Comment by suyogkokaje** [comment]
Okay. Thank you.

**Comment by suyogkokaje** [comment]
@akshitagupta15june please have a look.

**Review by akshitagupta15june — APPROVED** [review]
great work!

**Review by Komal-99 — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
@suyogkokaje your score added in sheet

**Comment by suyogkokaje** [comment]
Thank you @akshitagupta15june

**Pull request merged**
