### PR TITLE
Implement Face Swapping #1132

### PR DESCRIPTION
**Pull request by ADITYADAS1999**
# Related Issues or bug
  -Implement Face Swapping

Fixes: #1132 

# Proposed Changes
 - To Implement Face Swapping In awesome face operation folder

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
create a single folder only Face-swapping and make a folder of images inside it and keep all your images there because right now it looks kinda messy

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
add all images in a separate image folder in face-swap

**Comment by ADITYADAS1999** [comment]
i kept all images in "images" folder.

**Review by akshitagupta15june — APPROVED** [review]
Good work!

**Comment by ADITYADAS1999** [comment]
> 

Thank you 😊

**Pull request merged**
